// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PaulaPresentesWebMVC.Data;

#nullable disable

namespace PaulaPresentesWebMVC.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260521225419_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Carrinho", b =>
                {
                    b.Property<int>("IdCarrinho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_carrinho");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCarrinho"));

                    b.Property<DateTime?>("DataCriacaoCarrinho")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_criacao");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.HasKey("IdCarrinho");

                    b.HasIndex("IdCliente");

                    b.ToTable("Carrinho");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.CarrinhoItem", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdItem"));

                    b.Property<int>("IdCarrinho")
                        .HasColumnType("integer")
                        .HasColumnName("id_carrinho");

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("SubtotalItem")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal_item");

                    b.HasKey("IdItem");

                    b.HasIndex("IdCarrinho");

                    b.HasIndex("IdProduto");

                    b.ToTable("CarrinhoItem");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCliente"));

                    b.Property<bool?>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<string>("Bairro")
                        .HasColumnType("text")
                        .HasColumnName("bairro");

                    b.Property<string>("CEP")
                        .HasColumnType("text")
                        .HasColumnName("cep");

                    b.Property<string>("CPF")
                        .HasColumnType("text")
                        .HasColumnName("cpf");

                    b.Property<string>("Cidade")
                        .HasColumnType("text")
                        .HasColumnName("cidade");

                    b.Property<DateTime?>("DataCadastroCliente")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_cadastro");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_nascimento");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Estado")
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("Numero")
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .HasColumnType("text")
                        .HasColumnName("rua");

                    b.Property<string>("Senha")
                        .HasColumnType("text")
                        .HasColumnName("senha");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone");

                    b.HasKey("IdCliente");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Cupom", b =>
                {
                    b.Property<int>("IdCupom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cupom");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCupom"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<bool>("CupomAtivo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime?>("DataValidadeCupom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_validade");

                    b.Property<string>("TipoDesconto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_desconto");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_minimo");

                    b.HasKey("IdCupom");

                    b.ToTable("Cupom");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.MovimentacaoCaixa", b =>
                {
                    b.Property<int>("IdMovimentacaoCaixa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimentacao");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimentacaoCaixa"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimentacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("IdMovimentacaoCaixa");

                    b.ToTable("MovimentacaoCaixa");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.MovimentacaoEstoque", b =>
                {
                    b.Property<int>("IdMovimentacaoEstoque")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_movimentacao_estoque");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdMovimentacaoEstoque"));

                    b.Property<DateTime>("DataMovimentacaoEstoque")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_movimentacao_estoque");

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.HasKey("IdMovimentacaoEstoque");

                    b.HasIndex("IdProduto");

                    b.ToTable("MovimentacaoEstoque");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Pagamento", b =>
                {
                    b.Property<int>("IdPagamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pagamento");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPagamento"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<int?>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int?>("IdVenda")
                        .HasColumnType("integer")
                        .HasColumnName("id_venda");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasColumnType("numeric")
                        .HasColumnName("valor");

                    b.HasKey("IdPagamento");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdVenda");

                    b.ToTable("Pagamento");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedido"));

                    b.Property<string>("CodigoRastreio")
                        .HasColumnType("text")
                        .HasColumnName("codigo_rastreio");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_pedido");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("IdCliente")
                        .HasColumnType("integer")
                        .HasColumnName("id_cliente");

                    b.Property<int?>("PrazoFrete")
                        .HasColumnType("integer")
                        .HasColumnName("prazo_frete");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<string>("TipoFrete")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_frete");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.Property<decimal?>("ValorFrete")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_frete");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdCliente");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.PedidoItem", b =>
                {
                    b.Property<int>("IdPedidoItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPedidoItem"));

                    b.Property<int>("IdPedido")
                        .HasColumnType("integer")
                        .HasColumnName("id_pedido");

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal_item");

                    b.HasKey("IdPedidoItem");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdProduto");

                    b.ToTable("PedidoItem");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Produto", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProduto"));

                    b.Property<decimal?>("Altura")
                        .HasColumnType("numeric")
                        .HasColumnName("altura");

                    b.Property<string>("Categoria")
                        .HasColumnType("text")
                        .HasColumnName("categoria");

                    b.Property<string>("CodigoBarra")
                        .HasColumnType("text")
                        .HasColumnName("codigo_barra");

                    b.Property<decimal?>("Comprimento")
                        .HasColumnType("numeric")
                        .HasColumnName("comprimento");

                    b.Property<string>("Cor")
                        .HasColumnType("text")
                        .HasColumnName("cor");

                    b.Property<DateTime?>("DataCompra")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_compra");

                    b.Property<string>("Descricao")
                        .HasColumnType("text")
                        .HasColumnName("descricao");

                    b.Property<decimal?>("Largura")
                        .HasColumnType("numeric")
                        .HasColumnName("largura");

                    b.Property<string>("Marca")
                        .HasColumnType("text")
                        .HasColumnName("marca");

                    b.Property<string>("Nome")
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("numeric")
                        .HasColumnName("peso");

                    b.Property<decimal?>("PrecoCusto")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_custo");

                    b.Property<decimal?>("PrecoVenda")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_venda");

                    b.Property<int?>("QuantidadeEstoque")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_estoque");

                    b.Property<int?>("QuantidadeVendida")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade_vendida");

                    b.HasKey("IdProduto");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.ProdutoImagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_imagem");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdImagem"));

                    b.Property<string>("CaminhoImagem")
                        .HasColumnType("text")
                        .HasColumnName("caminho_imagem");

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    b.HasKey("IdImagem");

                    b.HasIndex("IdProduto");

                    b.ToTable("ProdutoImagem");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Venda", b =>
                {
                    b.Property<int>("IdVenda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_venda");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVenda"));

                    b.Property<DateTime>("DataVenda")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_venda");

                    b.Property<decimal>("Desconto")
                        .HasColumnType("numeric")
                        .HasColumnName("desconto");

                    b.Property<string>("Funcionario")
                        .HasColumnType("text")
                        .HasColumnName("funcionario");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric")
                        .HasColumnName("total");

                    b.HasKey("IdVenda");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.VendaItem", b =>
                {
                    b.Property<int>("IdVendaItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_venda_item");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdVendaItem"));

                    b.Property<int>("IdProduto")
                        .HasColumnType("integer")
                        .HasColumnName("id_produto");

                    b.Property<int>("IdVenda")
                        .HasColumnType("integer")
                        .HasColumnName("id_venda");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("numeric")
                        .HasColumnName("preco_unitario");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer")
                        .HasColumnName("quantidade");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("numeric")
                        .HasColumnName("subtotal");

                    b.HasKey("IdVendaItem");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdVenda");

                    b.ToTable("VendaItem");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Viagem", b =>
                {
                    b.Property<int>("IdViagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_viagem");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdViagem"));

                    b.Property<decimal>("CustoAlimentacao")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_alimentacao");

                    b.Property<decimal>("CustoIdaVolta")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_ida_volta");

                    b.Property<decimal>("CustoTotal")
                        .HasColumnType("numeric")
                        .HasColumnName("custo_total");

                    b.Property<DateTime>("DataViagem")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("data_viagem");

                    b.Property<decimal>("ValorTotalCompra")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_total_compra");

                    b.HasKey("IdViagem");

                    b.ToTable("Viagem");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Carrinho", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.CarrinhoItem", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Carrinho", "Carrinho")
                        .WithMany("Itens")
                        .HasForeignKey("IdCarrinho")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaulaPresentesWebMVC.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carrinho");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.MovimentacaoEstoque", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Pagamento", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido");

                    b.HasOne("PaulaPresentesWebMVC.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("IdVenda");

                    b.Navigation("Pedido");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Pedido", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.PedidoItem", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaulaPresentesWebMVC.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.ProdutoImagem", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Produto", "Produto")
                        .WithMany("Imagens")
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.VendaItem", b =>
                {
                    b.HasOne("PaulaPresentesWebMVC.Models.Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PaulaPresentesWebMVC.Models.Venda", "Venda")
                        .WithMany()
                        .HasForeignKey("IdVenda")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");

                    b.Navigation("Venda");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Carrinho", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("PaulaPresentesWebMVC.Models.Produto", b =>
                {
                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
